name: CD

# only manual trigger
on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Semantic version (e.g. v1.2.0)"
        required: true

jobs:
  build-and-release:
    name: 🚀 Build & Release
    runs-on: macos-latest
    environment:
      name: production
      # require reviewers in repo Settings → Environments → production
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache pub & Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
          key: ${{ runner.os }}-build-${{ hashFiles('**/pubspec.*', 'android/**/build.gradle') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android AAB
        run: flutter build apk --release

      - name: Build iOS IPA
        run: flutter build ios --simulator --release --no-codesign

      - name: Build Web
        run: flutter build web --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts-${{ github.event.inputs.release-tag }}
          path: |
            build/app/outputs/**/*.apk
            build/ios/ipa/**/*.app
            build/web/

    #   - name: Create GitHub Release
    #     uses: softprops/action-gh-release@v1
    #     with:
    #       tag_name: ${{ github.event.inputs.release-tag }}
    #       name: Release ${{ github.event.inputs.release-tag }}
    #     env:
    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Notify Slack (optional)
    #     if: success()
    #     uses: 8398a7/action-slack@v3
    #     with:
    #       payload: |
    #         { "text": "🚀 Release ${{ github.event.inputs.release-tag }} succeeded!" }
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
