name: CD

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Semantic version (e.g. v1.2.0)"
        required: true
      include-android:
        description: "Build Android?"
        required: false
        default: "true"
      include-ios:
        description: "Build iOS?"
        required: false
        default: "true"
      include-web:
        description: "Build Web?"
        required: false
        default: "true"

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

env:
  FLUTTER_CHANNEL: stable

jobs:
  build-android:
    if: ${{ github.event.inputs.include-android == 'true' }}
    name: 🤖 Android AAB
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Pub & Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.gradle
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml', 'android/**/build.gradle') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies (try offline, fallback online)
        run: |
          if ! flutter pub get --offline; then
            echo "⚠️ Cache miss – falling back to online pub get"
            flutter pub get
          fi

      - name: Build Android apk
        run: flutter build apk --release

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: android-aab-${{ github.event.inputs.release-tag }}
          path: build/app/outputs/**/*.apk

  build-ios:
    if: ${{ github.event.inputs.include-ios == 'true' }}
    name: 📱 iOS IPA
    runs-on: macos-latest
    environment: production
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies (try offline, fallback online)
        run: |
          if ! flutter pub get --offline; then
            echo "⚠️ Cache miss – falling back to online pub get"
            flutter pub get
          fi

      # Insert Fastlane Match or provisioning logic here if needed

      - name: Build iOS IPA
        run: flutter build ios --simulator

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-${{ github.event.inputs.release-tag }}
          path: build/ios/ipa/**/*.app

  build-web:
    if: ${{ github.event.inputs.include-web == 'true' }}
    name: 🌐 Web Bundle
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache Pub
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}

      - name: Install dependencies (try offline, fallback online)
        run: |
          if ! flutter pub get --offline; then
            echo "⚠️ Cache miss – falling back to online pub get"
            flutter pub get
          fi

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web Bundle
        uses: actions/upload-artifact@v4
        with:
          name: web-bundle-${{ github.event.inputs.release-tag }}
          path: build/web/
