# .github/workflows/ci.yml
name: Flutter Lint

on:
  push:
    branches: ["**"] # run on every push, any branch
  pull_request:
    branches: ["main", "develop"] # and on PRs targeting your protected branches

jobs:
  lint:
    name: 🧹 Format & Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: flutter format --set-exit-if-changed .

      - name: Run analyzer
        run: flutter analyze --no-fatal-warnings
